import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/context/AuthContext";
// import ChatBot from "@/components/ChatBot/ChatBot";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FIT Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-16`}
      >
        <script src="//code.tidio.co/yqa9hc8bhj10rsdjpvljsjjjqr08gjni.js" async></script>
        <AuthProvider>
          <Navbar />
          <div className="min-h-[100vh]">
            {children}
          </div>
          <Footer />
          <div className="fixed bottom-4 right-4 z-50">
            {/* <ChatBot /> */}

          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
